@extends('front-end.layouts.app')
@section('frontContent')
    <div id="page" class="site">

        <div id="content" class="site-content">
            <div class="page-header flex-middle">
                <div class="container">
                    <div class="inner flex-middle">
                        <h1 class="page-title">Politique</h1>
                        <ul id="breadcrumbs" class="breadcrumbs none-style">
                            <li><a href="index.html">Home</a></li>
                            <li class="active">Politique</li>
                        </ul>    
                    </div>
                </div>
            </div>
            <section class="typography">
                <div class="container">
                    <div class="row">
                        <div class="col-md-12">
                            <p>Privacy Policy
                                Effective Date:xxxx, 2024
                                1. Acceptance
                                We have created this Privacy Policy (the “Policy”) because we value users’ privacy. The Policy describes the types of information we may collect from you, or that you may provide, when you access Work4Connect (the “Site”). This Policy does not apply to information collected by any third party, including through any external website that may link to or be accessible from the Site. Please check directly with each such third party to avoid unfair surprises and misunderstandings.
                                Your use of this Site constitutes your acceptance of this Privacy Policy. If you do not agree with this Privacy Policy, you may not use our Site. This Policy may change from time to time, and the date of last update is indicated at the top of this page. Your continued use of this Site after we revise this Policy is deemed to be acceptance of the revisions, so please check this page from time to time for updates.
                                2. What information we collect
                                We may collect several types of information from and about users of our Site, including the following:
                                •	a) Personal Information: First Name, Last Name, Email, Phone number, University, Resume, Payment Details, login, password.
                                •	b) Voluntary Data: Information you voluntarily provide when you contact us for any reason, upload or otherwise send us.
                                We collect this information:
                                •	c) Directly from you when you provide it to us.
                                •	d) Automatically as you navigate through the Site.
                                3. How we use your information
                                We use information that we collect about you or that you provide to us, including any personal information:
                                •	a) To provide the services you requested.
                                •	b) To notify you about changes to our Site or any services we offer or provide through it.
                                •	c) To carry out our obligations and enforce our rights.
                                •	d) In any other way we may describe when you provide the information.
                                4. Disclosure of your information
                                We do not sell any of your personal information to 3rd parties. We may disclose personal information that we collect or you provide as described in this Policy:
                                •	a) To fulfill the purpose for which you provide it.
                                •	b) To contractors, service providers and other third parties we use to support our business.
                                •	c) To a buyer or other successor in the event of a merger, divestiture, restructuring, reorganization, dissolution or other sale or transfer of some or all of the Site's assets, whether as a going concern or as part of bankruptcy, liquidation or similar proceeding, in which personal information about our Site users is among the assets transferred.
                                •	d) We may, without restriction, disclose aggregated information about our users and information that does not identify any individual.
                                •	e) For any other purpose disclosed by us when you provide the information.
                                We may also disclose your personal information:
                                •	f) To comply with any court order, law or legal process, including to respond to any government or regulatory request.
                                •	g) If we believe disclosure is necessary or appropriate to protect the rights, property, or safety of the Site, our customers or others.
                                5. Cookie Policy
                                Cookies are small text files which a website may put on your computer or mobile device when you first visit a site or page. The cookie will help our Site, or another website, to recognize your device the next time you visit. For example, cookies can help us to remember your username and preferences, analyze how well our website is performing, or even allow us to recommend content we believe will be most relevant to you.
                                We may use cookies for the following reasons and purposes:
                                •	a) To provide the service you have asked for. Some cookies are essential so you can navigate through the website and use its features. Without these cookies, we would not be able to provide the services you’ve requested. For example, some cookies allow us to identify subscribers and ensure they can access the subscription only pages. If a subscriber opts to disable these cookies, the user will not be able to access all of the content that a subscription entitles them to. 
                                These cookies don't gather information about you that could be used for marketing or remembering where you've been on the internet. Essential cookies keep you logged in during your visit.
                                •	b) To improve your browsing experience. These cookies allow the website to remember choices you make, such as your language or region and they provide improved features. These cookies will help remembering your preferences and settings, including marketing preferences, remembering if you've filled in certain forms, so you're not asked to do it again, remembering if you've been to the Site before and restricting the number of times you're shown a particular advertisement. We might also use these cookies to highlight Site services that we think will be of interest to you based on your usage of the website.
                                •	c) Analytics.To improve your experience on our Site, we like to keep track of what pages and links are popular and which ones don't get used so much to help us keep our Site relevant and up to date. It's also very useful to be able to identify trends of how people navigate (find their way through) our Site and if they get error messages from web pages. This group of cookies, often called “analytics cookies” are used to gather this information. These cookies don't collect information that identifies you. The information collected is anonymous and is grouped with the information from everyone else’s cookies.
                                •	 We can then see the overall patterns of usage rather than any one person’s activity.
                                •	d)To show advertising that is relevant to your interests. We may sell space on our Site to advertisers. The resulting ads often contain cookies. These cookies are used to deliver adverts more relevant to you and your interests. They are also used to limit the number of times you see an advertisement as well as help measure the effectiveness of the advertising campaign. They are usually placed by advertising networks with our permission. They remember that you have visited a website and this information is shared with other organizations such as advertisers.
                                Most browsers allow you to turn off cookies. To do this, look at the “help” menu on your browser. Switching off cookies may restrict your use of the Site and/or delay or affect the way in which it operates.
                                6. Data security
                                Personal information you provide to us is stored on a password protected server accessible only by administrator. We use SSL. However, we cannot guarantee the security of your personal information transmitted to our Site because any transmission of information over the Internet has its inherent risks. Any transmission of personal information is at your own risk. We are not responsible for circumvention of any privacy settings or security measures contained on the Site. You are responsible for keeping your login credentials, if any, confidential.
                                7. Children’s privacy
                                Our Site is not directed to children under the age of 14. We do not knowingly collect any personal information about children under the age of 14. If we obtain actual knowledge that we have collected personal information about a child under the age of 14, that information will be immediately deleted from our database.
                                If a parent believes that his or her child has submitted personal information to us, he or she can contact us via e-mail. 
                                We will promptly delete the information upon learning that it relates to a child under the age of 14. 
                                Please note that it is possible some of this information may remain archived in web logs and back-up archives after we delete the information from our active database.
                                8. International transfer
                                Your information, including Personal Information, may be transferred to — and maintained on — computers located outside of your state, province, country or other governmental jurisdiction where the data protection laws may differ than those from your jurisdiction.
                                9. EU users’ rights.
                                This section of our Privacy Policy applies to the users of our platform in EU. We would like to inform you about your GDPR rights and how we safeguard them.
                                •	a)Your GDPR rights to be informed, to access, rectify, erase or restrict the processing of your personal information. You have the right to obtain free information about what personal data we have obtained about you, where it is stored, for how long, for what purposes it is used, to whom it was disclosed. You have the right to have us, without undue delay, rectify of inaccurate personal data concerning you. 
                                That means you can request we change your personal data in our records, or have you incomplete personal data completed. You have the “right to be forgotten,” i.e. to have us delete your personal information, without undue delay, if the data is no longer necessary in relation to the purposes for which it was collected. 
                                However, GDPR gives us the right to refuse erasure if we can demonstrate compelling legitimate grounds for keeping your information.
                                •	b) GDPR gives you the right to restrict processing if any of the following applies:
                                I.	If you contest the accuracy of your personal data, we will restrict processing it for a period enabling us to verify its accuracy.
                                II.	The processing is unlawful, and you oppose its erasure and request instead the restriction of its use.
                                III.	We no longer need your personal data for the purposes of the processing, but you require us to restrict processing for the establishment, exercise or defense of legal claims.
                                IV.	You have objected to processing pursuant to Article 21(1) of the GDPR pending the verification whether our legitimate grounds override yours.
                                •	c) Right to data portability. Upon request, we will provide you your personal data in our possession, in a structured, commonly used and machine-readable format. You have the right to transmit that data to another controller if doing so does not adversely affect the rights and freedoms of others.
                                •	d) Right to object.You can object, on grounds relating your particular situation, at any time, to processing of your personal information, if based on point (e) or (f) of Article 6(1) of the GDPR. We will then have to stop processing, unless we can demonstrate compelling legitimate grounds for the processing. If you object to the processing for direct marketing purposes, we will have to stop processing for these purposes.
                                •	e) Right to withdraw consent. GDPR grants you the right to withdraw your earlier given consent, if any, to processing of your personal data at any time.
                                •	f) Rights related to automated decision making. As a responsible business, we do not rely on any automated decision making, such as profiling.
                                10. Accessing and correcting your personal information
                                Please send us an e-mail to privacy@work4Connect.com to request access to, correct or delete any personal information that you have provided to us or to ask questions about this Privacy Policy. We reserve the right to refuse a request if we believe it would violate any law or cause the information to be incorrect. You can edit or delete your own information in your account settings.
                                À propos de Work4Connect
                                •	A propos
                                Work4Connect est une plateforme africaine proposant:
                                A nos prestataires:
                                •	Des offres de travail à distance à l’international dans les domaines de l’ingenierie, du conseil et de l’informatique pour les prestataires et pour les clients
                                •	Des offres de travail à l’international
                                        A nos clients :
                                -	Un pool d’experts
                                •	Centre d'aide
                                •	Contacts
                                •	Salle de presse
                                •	Équipe de Direction
                                •	Comment fonctionne Jooble
                                •	Carrières
                                Partenariat
                                Terms of service
                                Effective Date: January 29, 2025
                                1. Acceptance
                                We encourage you to read these Terms of Service (the “Terms”). This is a legally binding contract, even if you are just browsing through Work4Connect.org (the “Site”) without registering an account or contacting us. The term "you" refers to all Site visitors and users. Our Privacy Policy https://Work4Connect.com/info/privacy also governs your use of the Site. If you do not agree to accept these Terms or the Privacy Policy, you must exit the Site. Note that we may revise the aforementioned documents whenever we feel it is appropriate, sometimes without prior notification. If you continue visiting our Site after we have published the revised versions, this constitutes your acceptance of the changes. If you do not agree with any changes, you must exit the Site.
                                Agreeing to the Terms have effect with the following entities (Jooble entities):
                                •	Work4Connect” xxx, K, Lomé (TOGO)
                                All references to “Work4Connect” or “we” in the Terms are made to the entities above.
                                2. Venue
                                •	a) Neutral Venue. The Site allows companies to post jobs for any positions they need filled. OUR SITE IS A NEUTRAL VENUE. WE DISCLAIM ALL LIABILITY ARISING OUT OF USERS’ LISTINGS, INTERACTIONS AND TRANSACTIONS. WE DO NOT ENDORSE ANY PARTICULAR EMPLOYER OR ANY OTHER SITE USER, AND DO NOT GUARANTEE THAT ANY USER WILL PERFORM THEIR OBLIGATIONS SATISFACTORILY.
                                •	b) Third Party Content. A lot of the Site content (e.g., job listings, resumes, reviews, etc.) is provided by third parties. We also use third party services to support our Site. Such third parties are not owned or controlled by us. 
                                We assume no responsibility for, the content, privacy policies, or practices of any third party content. In addition, our Site will not and cannot censor or edit the content of any third-party website. You acknowledge that we will not be liable for any and all claims, demands and damages of any kind and nature arising out of or in any way connected from any and all potential liabilities arising from the use of any third-party network or content. 
                                We cannot guarantee the availability or performance of any third party services used to support the Site. Such third party services may change their operations without notice to us. Therefore, we shall not be liable for any outages, version changes, delivery delays, failures, bugs, or termination of third party network service. Third party networks have their own terms of use, and you must comply with any terms of use provided by any third party network.
                                3. Intellectual property
                                •	a) Our IP. All Site contents, registered and unregistered trademarks, designs, information and images (the “Intellectual Property”) belong to us and our content suppliers. 
                                The Intellectual Property is protected by international trademark, copyright, privacy, and other intellectual property laws. You obtain no interest in that Intellectual Property, provided, however, that you may download and view or print a copy of materials on this Site for personal use as long as you do not modify any content (including any copyright notice) in any way. All rights not expressly granted under these Terms are reserved by us. Unless expressly stated otherwise, you shall not copy, reproduce or replicate any Intellectual Property. We have the right but not the obligation to monitor and edit or remove any content submitted by users. We take no responsibility and assume no liability for any content posted by users or any third party.
                                •	b) Copyright Infringement Claims. Unauthorized copying, distribution, modification, public display, or public performance of copyrighted works is an infringement of the copyright holder’s rights. You agree that you will not use our Site to infringe anyone’s intellectual property rights. We will investigate copyright infringement claims if they are reported to us to compliance@Work4Connect.com
                                
                                4. Your obligations
                                By using this Site, you represent, warrant and agree that:
                                •	a) You are 18 years of age or older.
                                •	b) You will only use the Site for legal purposes, and you will remain responsible for complying with all laws and regulations applicable to your use of the Site.
                                •	c) You will only post truthful listings and reviews.
                                •	d) You will perform all obligations undertaken when working on a job or hiring someone via our Site.
                                •	e) You will provide a valid payment method information when necessary and pay all sums due when due.
                                •	f) It is your sole responsibility to ensure that the service providers or the employers are licensed, certified, insured, bonded to the extent that your assignments require.
                                •	g) You will not create duplicate accounts, and you will not share your account with anyone. You are solely responsible for all activity that occurs under your account.
                                •	h) Our Site may contain typographical errors or other inaccuracies.
                                •	i) Our Site content may not be copied for republication, either online or on paper, without our prior express written permission. However, you can share Site content via built-in social sharing buttons.
                                •	j) You will not submit unsolicited bulk or commercial messages ("spam") to our Site, other users or anyone else. Any unsolicited message must also not direct the recipient to any third party site or another resource.
                                •	k) You will not access our Site to gain a competitive advantage.
                                •	l) We have the right to refuse access, service or disable your account on our Site at any time for any reason or no reason without notice, explanation or liability of any kind.
                                •	m) You may not use any web spiders, bots, indexers, robots, crawlers, harvesters, or any other automatic process to access, acquire, copy or monitor any portion of the Site or any content, or in any way reproduce or circumvent the navigational structure or presentation of the Site or any content.
                                •	n) You will not interfere with the proper working of the Site. You will not impersonate any other person or entity, submit any false, defamatory, offensive, harassing material, or any material that violates another party's rights of privacy and publicity.
                                5. Remedies for breach of these terms
                                •	a) We may take any action that we deem necessary or appropriate if we believe that any user violates the Terms of Service, infringes any intellectual property right, privacy right or confidentiality principles, threatens anybody’s personal safety or uses offensive language. We may:
                                I.	disclose user’s identity to law enforcement agencies, to any third party claiming violation of their intellectual property or privacy right,
                                II.	block user’s IP address, notify user’s Internet Service Provider,
                                III.	suspend or terminate any account on our Site
                                IV.	moderate any content submitted to us,
                                V.	take any other action provided for in these Terms of Service or available under equity or law.
                                •	b) Since we cannot ensure that all material submitted to us is accurate and free of third party claims, we assume no liability for any action or inaction regarding transmissions, communications or content provided by any user or third party.
                                6. Disclaimer of warranty; Limitation of liability
                                •	a) THIS SITE AND ALL OF ITS CONTENT ARE PROVIDED "AS IS." YOU MUST NOT RELY ON ANY INFORMATION PUBLISHED ON OR LINKED TO THIS SITE WITHOUT FIRST MAKING YOUR OWN ENQUIRIES TO VERIFY IT IS ACCURATE, CURRENT AND COMPLETE. WE DO NOT MAKE, AND EXPRESSLY DISCLAIM, ANY REPRESENTATIONS, WARRANTIES, COVENANTS AND CONDITIONS, EXPRESS OR IMPLIED, ARISING OUT OF OPERATION OF LAW, COURSE OF PERFORMANCE, COURSE OF DEALING, USAGE OF TRADE OR OTHERWISE, INCLUDING ANY EXPRESS OR IMPLIED WARRANTIES AND CONDITIONS OF: MERCHANTABILITY; FITNESS FOR A PARTICULAR PURPOSE; NON-INFRINGEMENT; SAFETY; QUALITY; FREEDOM FROM DEFECTS OR THAT DEFECTS WILL BE CORRECTED; UNINTERRUPTED, VIRUS-FREE OR ERROR-FREE USE OF THIS SITE; OR ACCURACY, CURRENCY, RELIABILITY, COMPLETENESS OR APPROPRIATENESS RELATING TO THE CONTENT OF THIS SITE.
                                •	b) WE SHALL NOT BE LIABLE TO YOU FOR INDIRECT, INCIDENTAL, SPECIAL OR CONSEQUENTIAL DAMAGES, INCLUDING LOST PROFITS AND PROPERTY DAMAGE, EVEN IF WE WERE ADVISED OF THE POSSIBILITY OF SUCH DAMAGES, NOR SHALL WE BE HELD LIABLE FOR DELAY OR FAILURE IN PERFORMANCE RESULTING FROM CAUSES BEYOND OUR REASONABLE CONTROL. IN NO EVENT WILL OUR AGGREGATE LIABILITY EXCEED THE REFERRAL FEES RECEIVED. NO CLAIM, SUIT OR ACTION MAY BE BROUGHT AGAINST US AFTER SIX MONTHS FROM THE UNDERLYING CAUSE OF ACTION. SOME JURISDICTIONS DO NOT ALLOW THE EXCLUSION OF CERTAIN WARRANTIES OR THE LIMITATION, OR EXCLUSION OF LIABILITY FOR INCIDENTAL OR CONSEQUENTIAL DAMAGES, SO THE ABOVE LIMITATIONS MAY NOT APPLY TO YOU.
                                7. Indemnification
                                You agree to defendd, indemnify and hold harmless our company, its officers, directors, employees and agents, from and against any and all claims, damages, obligations, losses, liabilities, costs or debt, and expenses (including but not limited to attorney's fees) arising from:
                                I.	your use of and access to the Site;
                                II.	your violation of any provision of these Terms;
                                III.	your violation of any third party right, including without limitation any copyright, property, or privacy right;
                                IV.	or any claim that one of your user submissions caused damage to a third party.
                                8. Governing law & jurisdiction
                                These Terms and any action related thereto will be governed by the laws of England and Wales. Any controversy or claim arising out of or relating to these Terms, or the breach thereof, shall be settled by courts located in London, the UK.
                                9. General
                                •	a) Electronic Communications. You agree that all notices or other communications regarding your account and/or your use of the Site ("Communications"), may be provided to you electronically and you agree to receive all Communications from us in electronic form. You may print a copy of any Communications and retain it for your records. All electronic Communications will be considered just as legally binding as if they were in paper form. You may revoke your consent to receive Communications electronically, but if you revoke your consent to receive Communications electronically, we reserve the right to terminate your right to use our Site.
                                •	b) Relationship of the Parties. You and us are independent contractors to each other. There is no joint venture, partnership or employment relationship between us and any Site user.
                                •	c) Assignment. We may transfer, assign or subcontract the rights, interests or obligations under these Terms, at our sole discretion, without obtaining your consent.
                                •	d) Hyperlinks. You may link to our Site, as long as this is done in a fair way that does not negatively affect our reputation or business and does not suggest any form of association where there is none. We reserve the right to request that you withdraw any link and you agree to cooperate with us in causing any unauthorized framing or linking to terminate immediately.
                                •	e) Severability. Should any part of these Terms of Service be rendered or declared invalid by an appropriate authority, such invalidation of such part or portion of these Terms of Service should not invalidate the remaining portions thereof, and they shall remain in full force and effect.
                                •	f) No Waiver. Enforcement of these Terms of Service is solely in our discretion, and failure to enforce the Terms of Service in some instances does not constitute a waiver of our right to enforce them in other instances.
                                •	g)Prevailing Language. In the event of any discrepancy between the English original version of these Terms and any foreign language translation, the English version prevails.
                                10. Contact us
                                Please submit your inquiries to compliance@work4connect.com
                                Work4Connect Employer Account Terms
                                1. The product
                                These Work4Connect Employer Account Terms (“W4C Terms”) are part of the Terms. Posting a job advertisements on Work4Connect for payment or free, whether either directly or via an XML feed, you agree that you are solely responsible for content and target URLs.
                                2. Billing & Refund Policy
                                You will be charged based on the number of clicks you have received. The Work4Connect preserves exclusive right to determine click count which is binding. All prices are excusive of all taxes, including VAT. You will be charged all applicable taxes as required. All withholding tax remittances to the government are your sole responsibility and Work4Connect shall have no liability whatsoever, therefore. Your balance is the total cost accrued for promoting jobs plus applicable taxes, e.g. VAT.
                                Invoices may be provided to you via electronic mail.
                                Work4Connect’s Billing cycle is a calendar month. Your billing cycle begins on the date your Job Ad and payment method chosen are approved (e.g. credit card being approved). Depending on your billing address and the payment method you will contract with appropriate Work4Connect entity.
                                To cancel a paid subscription, you should go to the Job Settings and click Pause to delist a job ad from the premium listing or click Remove to delete a job ad permanently from your account. You should Pause or Remove every premium job ad.
                                Once all premium job ads are Paused or Removed, your outstanding balance will be charged according to Work4Connect billing cycle.
                                If you remove the payment method from your account, the outstanding balance will be charged at the moment when the payment method is being removed
                                Card processing is provided solely in favor of xxxx. Only one credit card per account is allowed.
                                We will first charge your card for an amount below USD xxx to validate your card and clear that amount in few days. Then
                                •	(a) if you choose a prepayment method (debit accounts), your card will only be charged for the amounts you enter and will be debited to your balance; your spending will be limited to your debit balance.
                                •	(b) if you choose a post-payment method (credit accounts) you will be charged once your total costs reach USD xxx and then every USD xxx or the 1st day of the following month, whichever event happens earlier.
                                If you choose currency other than US Dollars, when registering your account, the payments will be processed according to the exchange rate of your currency to US Dollars valid at the moment of transaction. This also means, that the amount charged from your card may differ slightly from the amount you have entered on debit accounts or the amount of your spending on credit accounts.
                                We reserve the right to determine, in our sole discretion, whether a reasonable basis exists to issue a refund of the fees we received from you upon your request. If we decide to issue a refund, we will deduct $xxx  commission from the refund issued to you. We will not issue any refunds if the fees we received from you are less than $xxx.
                                Terms of Service
                                This Terms of Service (the “Terms”) describes the rights and responsibilities that apply to your use of Reach Zone's websites, including but not limited to: Work4Connect, and any other service (collectively, the “Service”), each owned and operated by Work4Connect. ("Work4Connect ", “we”, “our” or “us”).
                                Please read the Terms carefully before using the Service. If you don't agree to the Terms, as well as Work4Connect's Privacy Policy (the “Privacy Policy”), you may not use the Service. If you are entering into the Terms on behalf of a company or other legal entity, you represent that you have the authority to bind such entity to the Terms. If you do not have such authority, you must not accept the Terms or use the Service on behalf of such entity. The Service is only available to you if you have entered the age of majority in your jurisdiction of residence and are fully able and competent to enter into, abide by and comply with the Terms.
                                Your Work4Connect Account. If you create an account on the Service (your “Account”), you are responsible for maintaining the security of your Account and its Content (as defined below), and you are fully responsible for all activities that occur under your Account and any other actions taken on the Service. You must not describe or assign Content to your Account in a misleading or unlawful manner, including in a manner intended to trade on the name or reputation of others, and Work4Connect may change or remove any description or keyword that it considers inappropriate or unlawful, or otherwise likely to cause Work4Connect liability. You must immediately notify Work4Connect of any unauthorized uses of your Account or any other breaches of security. Work4Connect will not be liable for any acts or omissions by you, including any damages of any kind incurred as a result of such acts or omissions.
                                Fees and Renewals. There will be no refunds or credits for partial months of job postings. Postings recur on a monthly basis and the user is required to update the auto-renewal on a monthly basis for each job post.
                                You take full responsibility for all taxes and fees of any nature associated with the Service, including any sales tax related to any purchase or sale of services or goods under the Terms. When purchasing or selling services or goods under the Terms, it is your responsibility to determine whether or not sales taxes apply to a transaction and to collect, report and remit the correct amounts to the appropriate authority.
                                Your Responsibilities. If you operate an Account, comment on a screenshot, post material to the Service, post links on the Service, or otherwise make (or allow any third party to make) material available by means of the Service (any such material, “Content”), you are entirely responsible for the content of, and any harm resulting from, that Content. That is the case regardless of whether the Content in question constitutes text or graphics. By making Content available, you represent and warrant that:
                                The downloading, copying and use of the Content will not infringe the proprietary rights, including but not limited to the copyright, patent, trademark or trade secret rights, of any third party;
                                If your employer has rights to intellectual property you create, you have either (i) received permission from your employer to post or make available the Content, including but not limited to any software, or (ii) secured from your employer a waiver as to all rights in or to the Content; you have fully complied with any third-party licenses relating to the Content, and have done all things necessary to successfully pass through to end users any required terms;
                                The Content does not contain or install any viruses or other harmful or destructive content; the Content is not spam, is not machine- or randomly-generated, and does not contain unethical or unwanted commercial content designed to drive traffic to third party sites or boost the search engine rankings of third party sites, or to further unlawful acts (such as phishing) or mislead recipients as to the source of the material (such as spoofing);
                                The Content is not obscene, libelous or defamatory, hateful or racially or ethnically objectionable, and does not violate the privacy or publicity rights of any third party; your Account is not getting advertised via unwanted electronic messages such as spam links on newsgroups, email lists, other blogs and web sites, and similar unsolicited promotional methods.
                                Your Account is not named in a manner that misleads your readers into thinking that you are another person or company. For example, your Account's URL or name is not the name of a person other than yourself or company other than your own; and you have, in the case of Content that includes computer code, accurately categorized and/or described the type, nature, uses and effects of the materials, whether requested to do so by Work4Connect or otherwise.
                                By uploading Content or otherwise providing Content to Work4Connect, you grant Work4Connect the right to use (including the right to host, index, cache and format) and display your Content in connection with providing the Service as well as otherwise on the Site and our marketing communications with you and other users and prospective users of the Service, including without limitation on our emails, marketing channels and other promotional materials (subject to the requirements set out in the Privacy Policy). To the extent we use your Content in our marketing communications, unless you expressly permit us to do otherwise, we will always cite you as the owner of such Content. This paragraph will survive the termination or expiry of the Terms.
                                Work4Connect reserves the right to refuse or remove any Content or terminate or deny access to your use of the Service for any reason whatsoever. Please read the Community Guidelines for rules and advice on what types of Content and uses of the Service are appropriate at Work4Connect
                                All Content uploaded are copyright © their respective owners.
                                If you delete Content, Work4Connect will use reasonable efforts to remove it from the Service, but you acknowledge that caching or references to the Content may not be made immediately unavailable.
                                Third Party Websites and Content. We have not reviewed, and cannot review, all of the material, including computer software, made available through the websites and webpages to which Work4Connect Zone links, and that link to Work4Connect. Work4Connect does not have any control over those non- Work4Connect websites and webpages, and is not responsible for their contents or their use. By linking to a non Work4Connect Zone website or webpage, Work4Connect Zone does not represent or imply that it endorses such website or webpage. You are responsible for taking precautions as necessary to protect yourself and your computer systems from viruses and other harmful or destructive content. Work4Connect disclaims any responsibility for any harm resulting from your use of non- Work4Connect websites and webpages.
                                Intellectual Property. All material available on the Service and all material and services provided by or through Work4Connect , its affiliates, subsidiaries, employees, agents, licensors or other commercial partners including, but not limited to, software, all informational text, software documentation, design of and “look and feel”, layout, photographs, graphics, audio, video, messages, interactive and instant messaging, design and functions, files, documents, images, or other materials, whether publicly posted or privately transmitted as well as all derivative works thereof (collectively, the “Materials”), are owned by us or our licensors or service providers, and are protected by copyright, trademark, trade secret and other intellectual property laws.
                                Subject to your compliance with the Terms, during the term of the Terms, Work4Connect grants to you a non-transferable, non-sublicensable, non-exclusive, revocable, limited purpose right to access and use the Materials that we make available to you.
                                If Work4Connect, in its sole discretion and without notice, considers that there is an immediate security or operational risk to the Service, any of its, your or a third party system, then Work4Connect may immediately suspend access to or use of the Service. The suspension of use and access is not a breach of the Terms. You acknowledge that the preservation of security, confidentiality and data is paramount. Work4Connect has no liability to you for suspending the Service under this provision.
                                This section does not apply to Content; however you agree that any ideas, suggestions, concepts, processes or techniques which you provide to Work4Connect related to the Service or Work4Connect or its business (“Feedback”) are and will be Work4Connect 's exclusive property without any compensation or other consideration payable to you by Work4Connect, and you do so of your own free will and volition. Work4Connect may or may not, in its sole discretion, use or incorporate the Feedback in whatever form or derivative Work4Connect may decide into the Service or its business or other products. You hereby assign all rights on a worldwide basis in perpetuity to Work4Connect in any Feedback and, as applicable, waive any moral rights.
                                For the purposes of the Terms and the Privacy Policy, “personal information” is any information about an identifiable individual, as defined in our Privacy Policy.
                                Reach Zone retains the right to use or share any Aggregated Data generated by anyone using the Service, including our users, for the purpose of enhancing and providing the Service. “Aggregated Data” means data does not contain personal information and which has been manipulated or combined to provide generalized, anonymous information. Where you choose to utilize or connect certain services from third parties with the Service, you agree that Work4Connect may share your lead data with such designated third parties. You are still responsible for any and all personal information that is part of any Content.
                                Changes. Work4Connect reserves the right, at its sole discretion, to modify or replace any part of the Terms. It is your responsibility to check the Terms periodically for changes. Your continued use of or access to the Service following the posting of any changes to the Terms constitutes acceptance of those changes. Work4Connect may also, in the future, offer new services and/or features through the Service (including, the release of new tools and resources). Such new features and/or services shall be subject to the Terms.
                                Disclaimer of Warranties. Your use of the Service and all Content forming part of or related to the Service, including any Content you upload or submit and any third party software and Content, are at your sole responsibility and risk. The Service are provided on an “as is” and “as available” basis. Work4Connect expressly disclaims all representations, warranties, or conditions of any kind with respect to the Service, whether express or implied, including, but not limited to, any implied warranties or conditions of merchantability, fitness for a particular purpose, accuracy, completeness, performance, system integration, quiet enjoyment, title, and non-infringement.
                                The service is offered and controlled by Work4Connect from its facilities in Togo and in the European Union. Work4Connect makes no representations that the service is appropriate or available for use in locations other than the European Union. Those who access or use the Service from other jurisdictions do so at their own volition and are responsible for compliance with local law. We handle complaints of copyright infringement in accordance with our Copyright Policy.
                                Limitation of Liability. You agree that, under no legal theory, including, but not limited to negligence, breach of warranty or condition, breach of contract or tort, will Work4Connect or its owners, officers, directors, affiliates, contractors, employees or agents, be liable to you or any third party acting on your behalf for any indirect, incidental, special, consequential, punitive, or exemplary damages or damages for loss of profits, goodwill, use, data, or other intangible losses or the cost of any substitute equipment, facilities or services (even if Work4Connect has been advised of the possibility of such damages), Work4Connect arising from or relating to the Terms or your use of or your inability to use the Service, or for any damages arising from or related to the Terms 's total aggregate liability from any and all claims under the Terms is limited to the total amounts you paid to Work4Connect in the one (1) year immediately preceding the occurrence of loss or damage. To the extent any province, state or jurisdiction does not allow the exclusion or the limitation of liability for consequential or incidental damages, Work4Connect 's liability in such province, state or jurisdiction will be limited to the furthest extent permitted by law. Notwithstanding the foregoing or anything else herein to the contrary, Work4Connect will not be liable to you or any third party acting on your behalf in any way with respect to a trial program or your provision of an individual's personal information to Work4Connect or through the Service. You further agree that the foregoing limitations will apply with respect to third party liability of any kind.
                                The foregoing limitations will also apply with respect to any damages incurred by reason of any content or services provided on any third party sites or otherwise provided by any third parties other than Work4Connect and received by you through or advertised on the Service or received by you on any third party sites. You also agree that Work4Connect will not be responsible or liable for any loss or damage of any kind incurred as the result of any interactions or dealings with advertisers or as the result of the presence of such advertisers on the Service.
                                With respect to any dispute arising out of or related to the Service and/or the Terms: (i) you hereby expressly give up your right to have a trial by jury; and (ii) you hereby expressly give up your right to participate as a member of a class of claimants, in any lawsuit including but not limited to class action lawsuits involving any such dispute.
                                You agree that you will not bring a claim under or related to the Terms more than one (1) year from when your claim first arose.
                                General Representation and Warranty. You represent and warrant that (i) your use of the Service will be in strict accordance with the Terms, the Privacy Policy, the Community Guidelines and all applicable laws and regulations (including without limitation any local laws or regulations in your country, state, city, or other governmental area, regarding online conduct and acceptable content, and including all applicable laws regarding the transmission of technical data exported from Togo or the European Union or the country in which you reside) and (ii) your use of the Service will not infringe or misappropriate the intellectual property rights of any third party.
                                Indemnification. You agree to indemnify, defend, and hold harmless Work4Connect , and its subsidiaries, affiliates, co-branders, all third-party advertisers, technology providers, service providers or other partners, and each of their respective officers, directors, agents, shareholders, employees and representatives (together, the “Indemnified Parties”), from and against any third party claim, demand, loss, damage, cost, or liability (including, reasonable attorneys' fees) (collectively and individually, “Claims”) incurred by or made against the Indemnified Parties in connection with any Claims arising out of or relating to the Terms, the Service, including but without limitation in relation to: (a) your use, non-use or misuse of, or connection to the Service and any Content; (b) your violation or alleged violation of the Terms; and (c) your violation of any rights, including intellectual property rights, of a third party and otherwise as set out herein. Work4Connect reserves the right, at your expense, to assume the exclusive defense and control of any matter for which you are required to indemnify Work4Connect and you agree to cooperate with Work4Connect 's defense of these Claims. You agree not to settle any matter without the prior written consent of Work4Connect. Work4Connect will use reasonable efforts to notify you of any such Claims upon becoming aware of it.
                                Miscellaneous. If there is any dispute between you and Work4Connect about or involving the Terms, the Service, you hereby agree that the dispute will be governed by and construed in accordance with the laws of the Togo without regard to its conflict of law provisions.
                                If any portion of the Terms is deemed unlawful, void or unenforceable by any arbitrator or court of competent jurisdiction, the Terms as a whole will not be deemed unlawful, void or unenforceable, but only that portion of the Terms that is unlawful, void or unenforceable will be stricken from the Terms.
                                You agree that the Terms are specifically enforceable by Work4Connect through injunctive relief and other equitable remedies without proof of monetary damages.
                                You agree that if Work4Connect does not exercise or enforce any legal right or remedy which is contained in the Terms (or which Work4Connect has the benefit of under any applicable law), this will not be taken to be a formal waiver of Work4Connect 's rights and that those rights or remedies will still be available to Work4Connect.
                                The Terms are the entire agreement between us related to the subject matter in the Terms. The Terms replace and supersede any other prior or contemporaneous agreement, representation or discussion, oral or written, and may not be changed except in writing signed by us, regardless of whether or not the parties act under an unsigned “electronic” agreement or rely on such an unsigned agreement.
                                Contacting Work4Connect. You may contact Work4Connect by email at info@work4Connect.com.
                                </p>
                        </div>
                    </div>
                </div>
            </section>
            
        </div>

</div><!-- #page -->
